GraphSAGE:
  encoder: [6, 64, 64, 8]
  decoder: [8, 64, 64, 4]

  nb_hidden_layers: 3
  size_hidden_layers: 64
  batch_size: 1
  nb_epochs: 400
  lr: 0.003
  max_neighbors: 64
  bn_bool: True
  subsampling: 1600
  r: 0.1

GAT:
  encoder: [6, 64, 64, 8]
  decoder: [8, 64, 64, 4]

  nb_hidden_layers: 3
  size_hidden_layers: 64
  batch_size: 1
  nb_epochs: 400
  lr: 0.003
  max_neighbors: 64
  bn_bool: True
  subsampling: 1600
  r: 0.1

PointNet:
  encoder: [6, 64, 64, 8]
  decoder: [8, 64, 64, 4]

  base_nb: 8
  batch_size: 1
  nb_epochs: 400
  lr: 0.003
  max_neighbors: 64
  subsampling: 1600
  r: 0.1

GUNet:
  encoder: [6, 64, 64, 8]
  decoder: [8, 64, 64, 4]

  layer: 'SAGE'
  pool: 'random'
  nb_scale: 5
  pool_ratio: [.75, .75, .666, .666]
  list_r: [.1, .2, .5, 1, 10]
  size_hidden_layers: 8
  dim_enc: 8
  batchnorm: True
  res: False

  batch_size: 1
  nb_epochs: 400
  lr: 0.003
  max_neighbors: 64
  subsampling: 1600
  r: 0.1

PointNet++:
  encoder: [6, 64, 64, 8]
  decoder: [8, 64, 64, 4]

  dim_enc: 8
  nb_scale: 7
  base_nb: 8
  pool_ratio: [.75, .75, .666, .666, .75, .666]
  list_r: [.1, .2, .4, .8, 1.6, 10]
  subsampling: 1600
  batch_size: 1
  nb_epochs: 400
  lr: 0.003
  max_neighbors: 64
  r: 0.1

GNO:
  encoder: [6, 64, 64, 8]
  decoder: [8, 64, 64, 4]
  kernel: [8, 64, 64, 64, 64]

  dim_rep: 8
  nb_iter: 5
  in_channels: 6
  out_channels: 4
  res: True
  bn_bool: True

  r: 0.1
  subsampling: 1600
  max_neighbors: 64
  batch_size: 1
  nb_epochs: 400
  lr: 0.003

MGNO:
  encoder: [6, 64, 64, 8]
  decoder: [8, 64, 64, 4]
  kernel: [8, 64, 64, 64, 64]
  local_nn: null

  dim_rep: 8
  nb_iter: 5
  in_channels: 6
  out_channels: 4
  res: True
  aggr: True
  bn_bool: True

  list_r: [0.1, 0.2, 0.5, 1., 10.]
  pool_ratio: [0.75, 0.75, 0.666, 0.666]
  subsampling: 1600
  max_neighbors: 64
  batch_size: 1
  nb_epochs: 400
  lr: 0.003
  r: 0.1
